# Generated by Django 3.2.4 on 2021-06-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='date1',
            field=models.DateField(default='1995-05-12'),
            preserve_default=False,
        ),
    ]
